spring:
  application:
    name: consumption
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/consumption
    username: root
    password: root_password
    driver-class-name: com.mysql.cj.jdbc.Driver